import odoo
from odoo.addons.mail.tests.common_controllers import MailControllerAttachmentCommon


@odoo.tests.tagged("-at_install", "post_install", "mail_controller")
class TestPortalAttachmentController(MailControllerAttachmentCommon):

    def test_attachment_upload_portal(self):
        """Test access to upload an attachment on portal"""
        record = self.env["mail.test.portal.no.partner"].create({"name": "Test"})
        token, bad_token, sign, bad_sign, _ = self._get_sign_token_params(record)
        self._execute_subtests_upload(
            record,
            (
                (self.user_public, False),
                (self.user_public, True, token),
                (self.user_public, True, sign),
                (self.guest, False),
                (self.guest, True, token),
                (self.guest, True, sign),
                (self.user_portal, False),
                (self.user_portal, False, bad_token),
                (self.user_portal, False, bad_sign),
                (self.user_portal, True, token),
                (self.user_portal, True, sign),
                (self.user_employee, True),
                (self.user_employee, True, bad_token),
                (self.user_employee, True, bad_sign),
                (self.user_employee, True, token),
                (self.user_employee, True, sign),
                (self.user_admin, True),
                (self.user_admin, True, bad_token),
                (self.user_admin, True, bad_sign),
                (self.user_admin, True, token),
                (self.user_admin, True, sign),
            ),
        )

    def test_independent_attachment_delete_portal(self):
        """Test access to delete an attachment on portal"""
        # Subtest format: (user, token, result, sign_token_params)
        record = self.env["mail.test.portal"].create({"name": "Test"})
        token, bad_token, sign, bad_sign, _ = self._get_sign_token_params(record)
        self._execute_subtests_delete(
            (
                (self.guest, False, False, token),
                (self.guest, True, False, token),
                (self.guest, False, False, sign),
                (self.guest, True, False, sign),
                (self.guest, False, False, bad_token),
                (self.guest, True, False, bad_token),
                (self.guest, False, False, bad_sign),
                (self.guest, True, False, bad_sign),
                (self.user_admin, False, True, token),
                (self.user_admin, True, True, token),
                (self.user_admin, False, True, sign),
                (self.user_admin, True, True, sign),
                (self.user_admin, False, True, bad_token),
                (self.user_admin, True, True, bad_token),
                (self.user_admin, False, True, bad_sign),
                (self.user_admin, True, True, bad_sign),
                (self.user_employee, False, False, token),
                (self.user_employee, True, False, token),
                (self.user_employee, False, False, sign),
                (self.user_employee, True, False, sign),
                (self.user_employee, False, False, bad_token),
                (self.user_employee, True, False, bad_token),
                (self.user_employee, False, False, bad_sign),
                (self.user_employee, True, False, bad_sign),
                (self.user_portal, False, False, token),
                (self.user_portal, True, False, token),
                (self.user_portal, False, False, sign),
                (self.user_portal, True, False, sign),
                (self.user_portal, False, False, bad_token),
                (self.user_portal, True, False, bad_token),
                (self.user_portal, False, False, bad_sign),
                (self.user_portal, True, False, bad_sign),
                (self.user_public, False, False, token),
                (self.user_public, True, False, token),
                (self.user_public, False, False, sign),
                (self.user_public, True, False, sign),
                (self.user_public, False, False, bad_token),
                (self.user_public, True, False, bad_token),
                (self.user_public, False, False, bad_sign),
                (self.user_public, True, False, bad_sign),
            ),
        )

    def test_attachment_delete_portal_linked_to_thread(self):
        """Test access to delete an attachment on portal associated with a thread"""
        # Subtest format: (user, token, result, sign_token_params)
        record = self.env["mail.test.portal"].create({"name": "Test"})
        token, bad_token, sign, bad_sign, _ = self._get_sign_token_params(record)
        self._execute_subtests_delete(
            (
                (self.guest, False, False),
                (self.guest, True, False),
                (self.guest, False, False, token),
                (self.guest, True, False, token),
                (self.guest, False, False, sign),
                (self.guest, True, False, sign),
                (self.guest, False, False, bad_token),
                (self.guest, True, False, bad_token),
                (self.guest, False, False, bad_sign),
                (self.guest, True, False, bad_sign),
                (self.user_admin, False, True),
                (self.user_admin, True, True),
                (self.user_admin, False, True, token),
                (self.user_admin, True, True, token),
                (self.user_admin, False, True, sign),
                (self.user_admin, True, True, sign),
                (self.user_admin, False, True, bad_token),
                (self.user_admin, True, True, bad_token),
                (self.user_admin, False, True, bad_sign),
                (self.user_admin, True, True, bad_sign),
                (self.user_employee, False, True),
                (self.user_employee, True, True),
                (self.user_employee, False, True, token),
                (self.user_employee, True, True, token),
                (self.user_employee, False, True, sign),
                (self.user_employee, True, True, sign),
                (self.user_employee, False, True, bad_token),
                (self.user_employee, True, True, bad_token),
                (self.user_employee, False, True, bad_sign),
                (self.user_employee, True, True, bad_sign),
                (self.user_portal, False, False),
                (self.user_portal, True, False),
                (self.user_portal, False, False, token),
                (self.user_portal, True, False, token),
                (self.user_portal, False, False, sign),
                (self.user_portal, True, False, sign),
                (self.user_portal, False, False, bad_token),
                (self.user_portal, True, False, bad_token),
                (self.user_portal, False, False, bad_sign),
                (self.user_portal, True, False, bad_sign),
                (self.user_public, False, False),
                (self.user_public, True, False),
                (self.user_public, False, False, token),
                (self.user_public, True, False, token),
                (self.user_public, False, False, sign),
                (self.user_public, True, False, sign),
                (self.user_public, False, False, bad_token),
                (self.user_public, True, False, bad_token),
                (self.user_public, False, False, bad_sign),
                (self.user_public, True, False, bad_sign),
            ),
            thread=record,
        )

    def get_delete_attachment_subtests(self, sign_token_params, different_result):
        token, bad_token, sign, bad_sign, partner = sign_token_params
        # Subtest format: (user, token, result, sign_token_params, author of the message)
        return (
            (self.guest, False, False),
            (self.guest, True, False),
            (self.guest, False, False, token),
            (self.guest, True, False, token),
            (self.guest, False, False, sign),
            (self.guest, True, False, sign),
            (self.guest, False, False, bad_token),
            (self.guest, True, False, bad_token),
            (self.guest, False, False, bad_sign),
            (self.guest, True, False, bad_sign),
            (self.guest, False, True, token, {"author": partner}),
            (self.guest, True, True, token, {"author": partner}),
            (self.guest, False, True, sign, {"author": partner}),
            (self.guest, True, True, sign, {"author": partner}),
            (self.guest, False, False, bad_token, {"author": partner}),
            (self.guest, True, False, bad_token, {"author": partner}),
            (self.guest, False, False, bad_sign, {"author": partner}),
            (self.guest, True, False, bad_sign, {"author": partner}),
            (self.guest, False, True, token, {"author": self.guest}),
            (self.guest, True, True, token, {"author": self.guest}),
            (self.guest, False, True, sign, {"author": self.guest}),
            (self.guest, True, True, sign, {"author": self.guest}),
            (self.guest, False, False, bad_token, {"author": self.guest}),
            (self.guest, True, False, bad_token, {"author": self.guest}),
            (self.guest, False, False, bad_sign, {"author": self.guest}),
            (self.guest, True, False, bad_sign, {"author": self.guest}),
            (self.user_admin, False, True),
            (self.user_admin, True, True),
            (self.user_admin, False, True, token),
            (self.user_admin, True, True, token),
            (self.user_admin, False, True, sign),
            (self.user_admin, True, True, sign),
            (self.user_admin, False, True, bad_token),
            (self.user_admin, True, True, bad_token),
            (self.user_admin, False, True, bad_sign),
            (self.user_admin, True, True, bad_sign),
            (self.user_admin, False, True, token, {"author": partner}),
            (self.user_admin, True, True, token, {"author": partner}),
            (self.user_admin, False, True, sign, {"author": partner}),
            (self.user_admin, True, True, sign, {"author": partner}),
            (self.user_admin, False, True, bad_token, {"author": partner}),
            (self.user_admin, True, True, bad_token, {"author": partner}),
            (self.user_admin, False, True, bad_sign, {"author": partner}),
            (self.user_admin, True, True, bad_sign, {"author": partner}),
            (self.user_admin, False, True, token, {"author": self.user_admin.partner_id}),
            (self.user_admin, True, True, token, {"author": self.user_admin.partner_id}),
            (self.user_admin, False, True, sign, {"author": self.user_admin.partner_id}),
            (self.user_admin, True, True, sign, {"author": self.user_admin.partner_id}),
            (
                self.user_portal,
                False,
                False,
                bad_token,
                {"author": self.user_portal.partner_id},
            ),
            (self.user_portal, True, False, bad_token, {"author": self.user_portal.partner_id}),
            (self.user_portal, False, False, bad_sign, {"author": self.user_portal.partner_id}),
            (self.user_portal, True, False, bad_sign, {"author": self.user_portal.partner_id}),
            (self.user_employee, False, False),
            (self.user_employee, True, False),
            (self.user_employee, False, False, token),
            (self.user_employee, True, False, token),
            (self.user_employee, False, False, sign),
            (self.user_employee, True, False, sign),
            (self.user_employee, False, False, bad_token),
            (self.user_employee, True, False, bad_token),
            (self.user_employee, False, False, bad_sign),
            (self.user_employee, True, False, bad_sign),
            (self.user_employee, False, False, token, {"author": partner}),
            (self.user_employee, True, False, token, {"author": partner}),
            (self.user_employee, False, False, sign, {"author": partner}),
            (self.user_employee, True, False, sign, {"author": partner}),
            (self.user_employee, False, False, bad_token, {"author": partner}),
            (self.user_employee, True, False, bad_token, {"author": partner}),
            (self.user_employee, False, False, bad_sign, {"author": partner}),
            (self.user_employee, True, False, bad_sign, {"author": partner}),
            (
                self.user_employee,
                False,
                False,
                token,
                {"author": self.user_employee.partner_id},
            ),
            (self.user_employee, True, False, token, {"author": self.user_employee.partner_id}),
            (self.user_employee, False, False, sign, {"author": self.user_employee.partner_id}),
            (self.user_employee, True, False, sign, {"author": self.user_employee.partner_id}),
            (
                self.user_employee,
                False,
                False,
                bad_token,
                {"author": self.user_employee.partner_id},
            ),
            (
                self.user_employee,
                True,
                False,
                bad_token,
                {"author": self.user_employee.partner_id},
            ),
            (
                self.user_employee,
                False,
                False,
                bad_sign,
                {"author": self.user_employee.partner_id},
            ),
            (
                self.user_employee,
                True,
                False,
                bad_sign,
                {"author": self.user_employee.partner_id},
            ),
            (self.user_portal, False, False),
            (self.user_portal, True, False),
            (self.user_portal, False, False, token),
            (self.user_portal, True, False, token),
            (self.user_portal, False, False, sign),
            (self.user_portal, True, False, sign),
            (self.user_portal, False, False, bad_token),
            (self.user_portal, True, False, bad_token),
            (self.user_portal, False, False, bad_sign),
            (self.user_portal, True, False, bad_sign),
            (self.user_portal, False, False, token, {"author": partner}),
            (self.user_portal, True, False, token, {"author": partner}),
            (self.user_portal, False, False, sign, {"author": partner}),
            (self.user_portal, True, False, sign, {"author": partner}),
            (self.user_portal, False, False, bad_token, {"author": partner}),
            (self.user_portal, True, False, bad_token, {"author": partner}),
            (self.user_portal, False, False, bad_sign, {"author": partner}),
            (self.user_portal, True, False, bad_sign, {"author": partner}),
            (self.user_portal, False, True, token, {"author": self.user_portal.partner_id}),
            (self.user_portal, True, True, token, {"author": self.user_portal.partner_id}),
            (self.user_portal, False, True, sign, {"author": self.user_portal.partner_id}),
            (self.user_portal, True, True, sign, {"author": self.user_portal.partner_id}),
            (
                self.user_portal,
                False,
                False,
                bad_token,
                {"author": self.user_portal.partner_id},
            ),
            (self.user_portal, True, False, bad_token, {"author": self.user_portal.partner_id}),
            (self.user_portal, False, False, bad_sign, {"author": self.user_portal.partner_id}),
            (self.user_portal, True, False, bad_sign, {"author": self.user_portal.partner_id}),
            (self.user_public, False, False),
            (self.user_public, True, False),
            (self.user_public, False, False, token),
            (self.user_public, True, False, token),
            (self.user_public, False, False, sign),
            (self.user_public, True, False, sign),
            (self.user_public, False, False, bad_token),
            (self.user_public, True, False, bad_token),
            (self.user_public, False, False, bad_sign),
            (self.user_public, True, False, bad_sign),
            (self.user_public, False, different_result, token, {"author": partner}),
            (self.user_public, True, different_result, token, {"author": partner}),
            (self.user_public, False, True, sign, {"author": partner}),
            (self.user_public, True, True, sign, {"author": partner}),
            (self.user_public, False, False, bad_token, {"author": partner}),
            (self.user_public, True, False, bad_token, {"author": partner}),
            (self.user_public, False, False, bad_sign, {"author": partner}),
            (self.user_public, True, False, bad_sign, {"author": partner}),
        )

    def test_attachment_delete_portal_no_partner(self):
        """Test access to delete an attachment on a portal document without partner which is
        associated with a message"""
        record = self.env["mail.test.portal.no.partner"].create({"name": "Test"})
        message = self.env["mail.message"].create({"model": record._name, "res_id": record.id})
        sign_token_params = self._get_sign_token_params(record)
        self._execute_subtests_delete(
            self.get_delete_attachment_subtests(sign_token_params, False),
            message=message,
        )

    def test_attachment_delete_portal_assigned_partner(self):
        """Test access to delete an attachment on a portal document with a partner which is
        associated with a message"""
        record = self.env["mail.test.portal"].create({"name": "Test"})
        sign_token_params = self._get_sign_token_params(record)
        record.partner_id = sign_token_params[-1]
        message = self.env["mail.message"].create({"model": record._name, "res_id": record.id})
        self._execute_subtests_delete(
            self.get_delete_attachment_subtests(sign_token_params, True),
            message=message,
        )
